version: '2.4'

services:
  streamlit:
    depends_on:
      - mongodb
    build:
      dockerfile: ./Dockerfile
      context: ./
    ports:
      - '8501:8501'
  mongodb:
    image: mongo:6-jammy
    restart: always
    environment:
      MONGO_INITDB_DATABASE: admin
      MONGO_INITDB_ROOT_USERNAME_FILE: /run/secrets/mongodb_root_username
      MONGO_INITDB_ROOT_PASSWORD_FILE: /run/secrets/mongodb_root_password
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
    secrets:
      - mongodb_root_username
      - mongodb_root_password

secrets:
  mongodb_root_username:
    file: /mongodb/.mongodb_root_username
  mongodb_root_password:
    file: /mongodb/.mongodb_root_password

volumes:
  mongodb_data_container: